apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
#    kubernetes.io/cluster-service: "true"
    app: kube-registry-volume
  name: kube-registry-volume
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
